import { Fugaz_One, Geist, Geist_Mono,Open_Sans } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/Context/AuthContext";
import Head from "./head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  
});

const opensans = Open_Sans({
  variable: "--font-opensans",
  subsets: ["latin"],
  
});

const fugaz = Fugaz_One({
   variable: "--font-fugaz",
  subsets: ["latin"],
  weight: ["400"]

})

export const metadata = {
  title: "Next",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const header = (
    <header className="p-4 sm:p-8 flex items-center justify-between  " >
      <h1 className= {`text-base sm:text-lg textGradient  ${fugaz.className}`} >
        Moodle
      </h1>
      
    </header>
  )
  const footer = (
    <footer className="p-4 sm:8">
      <p className={`text-center text-indigo-600 ${fugaz.className}`}>Created with 💙</p>
    </footer>
  )
    
  
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <Head></Head>
      <AuthProvider> 
      <body className={`w-full max-width-[1000px] text-sm sm:text-base min-h-full flex flex-col ${opensans.variable} ${opensans.className}`}>
        {header}
        {children}
        {footer}
        </body>
        </AuthProvider>
        
    </html>
  );
}
//we used authprovider in layout because,the layout also wraps the whole application
